
SRC = ft_printf.c ft_itoa_hex.c ft_printf_utils.c  ft_itoa.c ft_strncmp.c


HEADER = includes/ft_printf.h

OBJ = ${SRC:.c=.o}

CC = cc

CCFLAGS = -Wall -Wextra -Werror

NAME = libftprintf.a

.c.o:
	${CC} ${CCFLAGS} -c $< -o $@

all: ${NAME}

$(NAME): ${OBJ}
	ar rcs ${NAME} ${OBJ} ${HEADER}

clean:
	rm -f ${OBJ}
fclean: clean
	rm -f ${NAME}

re: fclean all
